[project]
name = "comida.app_backend"
version = "0.1.0"
description = "Backend for comida.app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.139.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
]
