name: Deploy backend to EC2

on:
  push:
    branches:
      - main # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH into EC2 and pull the latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/mvp
            git reset --hard HEAD   # Discard local changes
            git clean -fd           # Remove untracked files
            git pull origin main
            npm run copy:server
            cd backend
            npm ci
            npm run build
            pm2 restart api
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and run seed script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/mvp/backend
            npm run seed
