name: uploadToS3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'
        
    - name: Installs Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Creates .env file
      run: |
        echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> ./frontend/.env

    - name: Installs dependencies and builds project
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Sync files to S3
      run: aws s3 sync ./frontend/dist s3://${{ secrets.AWS_S3_BUCKET }} --delete

